config/routes.rb
Rails.application.routes.draw do
  get 'index/teste'
  post 'index/questions', to: 'index#questions', as: 'sign_up'
  get 'index/questions', to: 'index#questions', as: 'questions'
  post 'index/result', to: 'index#result', as: 'result_post'
  get 'index/result', to: 'index#result', as: 'result_get'
  get 'index/submit-token', to: 'index#submit_token', as: 'submit_token'
  get 'index/verify-token', to: 'index#verify_token', as: 'verify_token'
  get 'index/update-token', to: 'index#update_token', as: 'update_token'
  get 'index/index', to: 'index#index', as: 'index'

  root to: 'index#index'

  # match '*path', to: redirect('/404'), via: :all
end

app/views/index/_answer.erb
<!--<%#= label_tag "a#{ question_counter }#{ answer_counter }", answer.description, class: "waves-effect waves-light btn q#{ question_counter }" %> <br> <br>-->
<p class="flow-text answr  <%= "answr-#{ answer_counter }" %>">
<label class="">
  <%= radio_button_tag "q#{ question_counter }", answer.id, false, id: "a#{ question_counter }#{ answer_counter }", class: "q#{ question_counter } with-gap" %>
  <span class="over-t  "><%= answer.description %></span>
</label>
</p>

app/views/index/_question.erb
<div class="field content_q<%= question_counter %> card-content col s12 ">
  <!--  pergunta-->
 <%= label_tag "label_q#{ question_counter }", question.question.description%> <br>

  <div class="divider-px ">
    <span class="gradient-45deg-light-blue-cyan progress-b"></span>
  </div>
  <!--  respostas-->
  <%= render partial: "answer", collection: question.answers.shuffle, locals: {question_counter: question_counter} %>
</div>

app/views/index/index.html.erb
<%= form_tag(sign_up_path, :method => "post") do %>

  <div class="row">

    <h2 class="center">Cidadão TOauth</h2>

  <div class="card z-depth-3 center-block col s10 m6 offset-s1 offset-m3" style=" position:relative; top:120px;">


      <% if flash[:notice] %>
        <div class="red-text" role="alert" style="margin: 10px"><%= flash[:notice] %></div>
      <% end %>

      <br>
      <div class="input-field col s12 m8 ">
        <i class="material-icons prefix">account_circle</i>
        <input id="icon_prefix" name="cpf" placeholder="CPF (apenas números)" pattern="\d*" type="text" maxlength="11" class="validate" data-length="11">

      </div>

      <div class="col s4 m4 offset-s2">
        <!--          <button class="waves-effect waves-light btn-floating left" style="margin-top: 20px">-->
        <!--            <i class="large material-icons">trending_flat</i></button>-->
        <button class="btn waves-effect waves-light left" type="submit" name="action" style="margin-top: 20px">Iniciar
          <i class="material-icons right">send</i>
        </button>
      </div>

    </div>

  </div>


  <% if params[:value] != nil %>
    <%= params[:value] %>
  <% end %>


<% end %>

app/views/index/questions.html.erb
<%= form_tag result_post_path, method: 'post' do %>

  <% if cookies.encrypted[:formulario_enviado] == nil || cookies.encrypted[:formulario_enviado] || cookies.encrypted[:user_request_id] == nil %>
    <%= 'Acesso negado' %>
  <% else %>
    <div class="deep-purple bar "></div>
    <div class="row">

      <h2 class="center">Cidadão TOauth</h2>

    <div class="col s12">

      <div class="card  col s10 m8 l6 offset-m1 offset-m2 offset-l3 " >

        <% questions = UserRequest.find(cookies.encrypted[:user_request_id]).request_questions %>
        <%= render partial: "question", collection: questions %>

        <div class="btn deep-purple darken-3 waves-effect back2 right" > Voltar</div>
        <div class="btn deep-purple darken-3 waves-effect back3 right" > Voltar</div>


        <div class="row box">
          <div>
          <%= button_tag "Enviar Respostas", class: "btn waves-effect waves-light blue sub actb col s5", style: "margin: 10px" %>
          </div>
          <div class="btn deep-purple darken-3 waves-effect rr right col s5 actb z-depth-1" style="margin: 10px">
            REFAZER RESPOSTAS
          </div>
        </div>

      </div>
      </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function () {
            $('.content_q1').hide();
            $('.content_q2').hide();
            $('.sub').hide();
            $('.rr').hide();
            $('.back2').hide();
            $('.back3').hide();

            $(".q0").click(function () {
                setTimeout(function () {
                    $('.content_q0').fadeOut('fast', function () {
                        $('.progress-b').addClass('progress-b2')
                        $('.content_q1').fadeIn('fast');
                        $('.back2').show();
                    });
                }, 400);
            });

            $(".q1").click(function () {
                setTimeout(function () {
                    $('.content_q1').fadeOut('fast', function () {
                        $('.progress-b2').addClass('progress-b3')
                        $('.content_q2').fadeIn('fast');
                        $('.back2').hide();
                        $('.back3').show();
                    });
                }, 400);
            });

            $(".q2").click(function () {
                setTimeout(function () {
                    $('.content_q2').fadeOut('fast', function () {
                        $('.back3').hide();
                        $('.sub').fadeIn('fast');
                        $('.rr').fadeIn('fast');
                    });
                }, 400);
            });

            $(".back2").click(function () {
                setTimeout(function () {
                    // $('.divider-px span').removeClass('progress-back1')
                    // $('.divider-px span').addClass('progress-back')
                    $('.progress-b2').removeClass('progress-b2')
                    $('.content_q1').hide();
                    $('.back2').hide();
                    $('.content_q0').fadeIn('fast');
                }, 400);
            });

            $(".back3").click(function () {
                setTimeout(function () {
                    // $('.progress-b3').removeClass('progress-back')
                    // $('.divider-px span').addClass('progress-back1')
                    $('.progress-b3').removeClass('progress-b3')
                    $('.content_q2').hide();
                    $('.back3').hide();
                    $('.content_q1').fadeIn('fast');
                    $('.back2').show();
                }, 400);
            });

            $(".rr").click(function () {
                setTimeout(function () {
                    $('.rr').hide();
                    $('.sub').hide();
                    $('.content_q0').fadeIn('show');
                }, 400);
            });
        });
    </script>
  <% end %>
<% end %>

app/views/index/result.html.erb
<% if cookies.encrypted[:formulario_enviado] == false %>
  Acesso negado
<% else %>
  <div class="container" style="width: 70%; margin-top: 100px;">

    <div class="row">
      <div class="col s12 m8 l8 push-m2 push-l2 card">
        <div class="center">

          <% if cookies.encrypted[:resultado] != nil and !cookies.encrypted[:resultado] %>
            <div class="row">
              <br>
              <img src="/images/desapontado.png" width="50px"><br>
              <p>Suas informações não conferem. <br>Tente novamente em alguns minutos.</p>

            </div>

          <% elsif cookies.encrypted[:resultado] != nil and cookies.encrypted[:resultado] %>
            <div class="row">
              <br>
              <img src="/images/happy.png" width="50px"><br>
              <p>Parabéns!</p><br>

              <%#= link_to "Prosseguir", submit_token_path(token: cookies.encrypted[:user_token]), class: 'btn' %>
              <%= link_to "Prosseguir", "http://cidadao.to.gov.br/api/registrar?token=#{cookies.encrypted[:user_token]}", class: 'btn' %>
            </div>
          <% end %>
        </div>

      </div>
    </div>

  </div>
<% end %>